import { DataTypes } from 'sequelize';

export default (sequelize) => {
  const TopicGroup = sequelize.define('TopicGroup', {
    id: {
      type: DataTypes.UUID,
      defaultValue: DataTypes.UUIDV4,
      primaryKey: true
    },
    name: {
      type: DataTypes.STRING,
      allowNull: false
    },
    description: {
      type: DataTypes.TEXT,
      allowNull: true
    },
    embedding: {
      type: DataTypes.JSONB,
      allowNull: false
    },
    autoGenerated: {
      type: DataTypes.BOOLEAN,
      defaultValue: true
    },
    ticketCount: {
      type: DataTypes.INTEGER,
      defaultValue: 0
    }
  }, {
    tableName: 'topic_groups',
    timestamps: true
  });

  TopicGroup.associate = (models) => {
    TopicGroup.hasMany(models.Ticket, { foreignKey: 'topicGroupId' });
  };

  return TopicGroup;
};
