/**
 * Сервис автоматической группировки тикетов по тематике.
 *
 * Алгоритм:
 * 1. Генерируем embedding для title + description тикета
 * 2. Сравниваем cosine similarity с embeddings всех существующих TopicGroup
 * 3. Если max similarity >= порог → привязываем к группе
 * 4. Если ниже → создаём новую группу
 */

import { getModels } from '../models/index.js';
import { generateEmbedding, cosineSimilarity } from './mlModel.js';

const DEFAULT_THRESHOLD = 0.75;

/**
 * Получить порог сходства из настроек
 */
async function getThreshold() {
  try {
    const { SystemSettings } = getModels();
    const setting = await SystemSettings.findOne({ where: { key: 'grouping.similarityThreshold' } });
    return setting ? parseFloat(setting.value) : DEFAULT_THRESHOLD;
  } catch {
    return DEFAULT_THRESHOLD;
  }
}

/**
 * Классифицировать тикет — найти или создать тематическую группу.
 *
 * @param {string} title
 * @param {string} description
 * @returns {{ groupId: string, groupName: string, isNew: boolean, score: number }}
 */
export async function classifyTicket(title, description) {
  const { TopicGroup } = getModels();

  const text = `${title} ${description}`;
  const embedding = await generateEmbedding(text);
  const threshold = await getThreshold();

  // Загружаем все группы
  const groups = await TopicGroup.findAll();

  let bestMatch = null;
  let bestScore = 0;

  for (const group of groups) {
    const groupEmbedding = group.embedding;
    if (!groupEmbedding || !Array.isArray(groupEmbedding)) continue;

    const score = cosineSimilarity(embedding, groupEmbedding);
    if (score > bestScore) {
      bestScore = score;
      bestMatch = group;
    }
  }

  if (bestScore >= threshold && bestMatch) {
    // Обновляем embedding группы (скользящее среднее)
    const count = bestMatch.ticketCount || 1;
    const newEmbedding = bestMatch.embedding.map((val, i) =>
      (val * count + embedding[i]) / (count + 1)
    );

    await bestMatch.update({
      embedding: newEmbedding,
      ticketCount: count + 1
    });

    return {
      groupId: bestMatch.id,
      groupName: bestMatch.name,
      isNew: false,
      score: bestScore
    };
  }

  // Создаём новую группу
  const groupName = extractGroupName(title);

  const newGroup = await TopicGroup.create({
    name: groupName,
    embedding: Array.from(embedding),
    autoGenerated: true,
    ticketCount: 1
  });

  return {
    groupId: newGroup.id,
    groupName: newGroup.name,
    isNew: true,
    score: 0
  };
}

/**
 * Переклассифицировать все тикеты (сброс и пересоздание групп).
 * Запускается фоново.
 */
export async function reclassifyAll() {
  const { Ticket, TopicGroup } = getModels();

  // Удаляем все автогенерированные группы
  await TopicGroup.destroy({ where: { autoGenerated: true } });

  // Сбрасываем topicGroupId у всех тикетов
  await Ticket.update({ topicGroupId: null }, { where: {} });

  // Загружаем все тикеты
  const tickets = await Ticket.findAll({
    attributes: ['id', 'title', 'description'],
    order: [['createdAt', 'ASC']]
  });

  let classified = 0;
  for (const ticket of tickets) {
    try {
      const result = await classifyTicket(ticket.title, ticket.description);
      await ticket.update({ topicGroupId: result.groupId });
      classified++;
    } catch (err) {
      console.error(`[ML] Ошибка классификации тикета ${ticket.id}:`, err.message);
    }
  }

  console.log(`[ML] Переклассификация завершена: ${classified}/${tickets.length} тикетов`);
  return { classified, total: tickets.length };
}

/**
 * Извлечь короткое имя группы из заголовка тикета.
 * Берём первые 5 значимых слов.
 */
function extractGroupName(title) {
  const stopWords = new Set([
    'не', 'в', 'на', 'с', 'и', 'по', 'из', 'к', 'у', 'за', 'от', 'до',
    'при', 'для', 'о', 'а', 'но', 'что', 'это', 'как', 'мне', 'мой',
    'the', 'is', 'in', 'on', 'at', 'to', 'for', 'of', 'a', 'an'
  ]);

  const words = title
    .replace(/[^\p{L}\p{N}\s]/gu, '')
    .split(/\s+/)
    .filter(w => w.length > 2 && !stopWords.has(w.toLowerCase()));

  const name = words.slice(0, 5).join(' ');
  return name || title.slice(0, 50);
}
