import { getModels } from '../models/index.js';
import { reclassifyAll } from '../services/topicGrouping.js';
import { cosineSimilarity, generateEmbedding } from '../services/mlModel.js';

/**
 * GET /api/topic-groups
 */
export async function listTopicGroups(req, res) {
  const { TopicGroup } = getModels();

  const groups = await TopicGroup.findAll({
    attributes: ['id', 'name', 'description', 'autoGenerated', 'ticketCount', 'createdAt', 'updatedAt'],
    order: [['ticketCount', 'DESC']]
  });

  res.json({ data: groups });
}

/**
 * GET /api/topic-groups/:id
 */
export async function getTopicGroup(req, res) {
  const { TopicGroup, Ticket, User } = getModels();

  const group = await TopicGroup.findByPk(req.params.id, {
    include: [{
      model: Ticket,
      attributes: ['id', 'number', 'title', 'status', 'priority', 'createdAt'],
      include: [{ model: User, as: 'author', attributes: ['id', 'displayName'] }]
    }]
  });

  if (!group) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Группа не найдена' } });
  }

  res.json({
    data: {
      id: group.id,
      name: group.name,
      description: group.description,
      autoGenerated: group.autoGenerated,
      ticketCount: group.ticketCount,
      createdAt: group.createdAt,
      tickets: group.Tickets || []
    }
  });
}

/**
 * PUT /api/topic-groups/:id
 */
export async function updateTopicGroup(req, res) {
  const { TopicGroup } = getModels();

  const group = await TopicGroup.findByPk(req.params.id);
  if (!group) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Группа не найдена' } });
  }

  const { name, description } = req.body;
  if (name) group.name = name;
  if (description !== undefined) group.description = description;

  await group.save();
  res.json({ data: group });
}

/**
 * DELETE /api/topic-groups/:id
 */
export async function deleteTopicGroup(req, res) {
  const { TopicGroup, Ticket } = getModels();

  const group = await TopicGroup.findByPk(req.params.id);
  if (!group) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Группа не найдена' } });
  }

  // Открепляем тикеты
  await Ticket.update({ topicGroupId: null }, { where: { topicGroupId: group.id } });
  await group.destroy();

  res.status(204).send();
}

/**
 * POST /api/topic-groups/:id/merge/:otherId
 */
export async function mergeTopicGroups(req, res) {
  const { TopicGroup, Ticket } = getModels();

  const target = await TopicGroup.findByPk(req.params.id);
  const source = await TopicGroup.findByPk(req.params.otherId);

  if (!target || !source) {
    return res.status(404).json({ error: { code: 'NOT_FOUND', message: 'Одна из групп не найдена' } });
  }

  // Переносим тикеты из source в target
  await Ticket.update(
    { topicGroupId: target.id },
    { where: { topicGroupId: source.id } }
  );

  // Пересчитываем embedding (среднее)
  const totalCount = target.ticketCount + source.ticketCount;
  if (target.embedding && source.embedding) {
    const newEmbedding = target.embedding.map((val, i) =>
      (val * target.ticketCount + source.embedding[i] * source.ticketCount) / totalCount
    );
    target.embedding = newEmbedding;
  }

  target.ticketCount = totalCount;
  await target.save();

  // Удаляем source
  await source.destroy();

  res.json({ data: target });
}

/**
 * POST /api/topic-groups/reclassify
 */
export async function reclassifyAllTickets(req, res) {
  // Запускаем фоново
  res.json({ data: { message: 'Переклассификация запущена', status: 'processing' } });

  try {
    const result = await reclassifyAll();
    console.log(`[ML] Reclassify done: ${result.classified}/${result.total}`);
  } catch (err) {
    console.error('[ML] Reclassify error:', err.message);
  }
}
