import { el, clearEl } from '../utils/dom.js';
import { MainLayout } from '../components/layout/MainLayout.js';
import { Button } from '../components/ui/Button.js';
import { Badge } from '../components/ui/Badge.js';
import { Spinner } from '../components/ui/Spinner.js';
import { Toast } from '../components/ui/Toast.js';
import { formatDateTime } from '../utils/format.js';

export class TopicGroupsPage {
  constructor(router) {
    this.router = router;
    this.groups = [];
    this.selectedGroup = null;
  }

  async render(container) {
    clearEl(container);

    const user = window.__auth.getUser();
    const layout = new MainLayout({ user, router: this.router, auth: window.__auth });
    layout.mount(container);

    this.content = layout.getContent();
    this._renderContent();
    await this._loadGroups();
  }

  _renderContent() {
    clearEl(this.content);

    this.content.appendChild(el('div', { class: 'page-header' }, [
      el('h1', {}, 'Тематические группы'),
      el('div', { class: 'flex gap-sm' }, [
        new Button({ text: '\u2190 Назад', variant: 'ghost', onClick: () => this.router.navigate('/') }).el
      ])
    ]));

    this.listEl = el('div', { class: 'flex-col gap-sm' });
    this.content.appendChild(this.listEl);

    this.detailEl = el('div');
    this.content.appendChild(this.detailEl);
  }

  async _loadGroups() {
    clearEl(this.listEl);
    new Spinner().mount(this.listEl);

    try {
      const api = window.__api;
      const res = await api.get('/topic-groups');
      this.groups = res.data || [];
      this._renderGroups();
    } catch (err) {
      clearEl(this.listEl);
      Toast.error(err.message);
    }
  }

  _renderGroups() {
    clearEl(this.listEl);

    if (this.groups.length === 0) {
      this.listEl.appendChild(el('div', { class: 'empty-state' }, [
        el('div', { class: 'empty-state__icon' }, '\uD83D\uDCC2'),
        el('div', { class: 'empty-state__title' }, 'Нет тематических групп'),
        el('div', { class: 'empty-state__text' }, 'Группы создаются автоматически при создании тикетов')
      ]));
      return;
    }

    // Сетка карточек
    const grid = el('div', { class: 'stats-grid' });

    for (const group of this.groups) {
      const card = el('div', {
        class: 'stat-card card--hoverable',
        onClick: () => this._loadGroupDetail(group.id)
      });

      card.appendChild(el('div', { class: 'stat-card__label' },
        group.autoGenerated ? 'Автоматическая' : 'Ручная'
      ));
      card.appendChild(el('div', { class: 'stat-card__value' }, String(group.ticketCount)));
      card.appendChild(el('div', {
        style: { fontSize: 'var(--font-size-sm)', fontWeight: 'var(--font-weight-medium)', marginTop: 'var(--space-xs)' }
      }, group.name));

      grid.appendChild(card);
    }

    this.listEl.appendChild(grid);
  }

  async _loadGroupDetail(groupId) {
    clearEl(this.detailEl);

    const spinner = new Spinner();
    spinner.mount(this.detailEl);

    try {
      const api = window.__api;
      const res = await api.get(`/topic-groups/${groupId}`);
      this._renderGroupDetail(res.data);
    } catch (err) {
      clearEl(this.detailEl);
      Toast.error(err.message);
    }
  }

  _renderGroupDetail(group) {
    clearEl(this.detailEl);

    const card = el('div', { class: 'card mt-lg' });

    card.appendChild(el('div', { class: 'flex items-center justify-between mb-md' }, [
      el('h2', {}, group.name),
      new Badge(`${group.ticketCount} тикетов`, 'in-progress').el
    ]));

    if (group.description) {
      card.appendChild(el('p', { class: 'text-secondary text-sm mb-md' }, group.description));
    }

    // Список тикетов группы
    if (group.tickets && group.tickets.length > 0) {
      const ticketList = el('div', { class: 'flex-col gap-xs' });

      for (const t of group.tickets) {
        const row = el('a', {
          href: `#/tickets/${t.id}`,
          class: 'flex items-center justify-between',
          style: {
            padding: 'var(--space-sm) var(--space-md)',
            borderRadius: 'var(--radius-sm)',
            fontSize: 'var(--font-size-sm)',
            transition: 'background var(--transition-fast)'
          }
        }, [
          el('span', {}, `#${t.number} ${t.title}`),
          el('span', { class: 'text-muted text-xs' }, t.status)
        ]);

        row.addEventListener('mouseenter', () => row.style.background = 'var(--color-surface-hover)');
        row.addEventListener('mouseleave', () => row.style.background = '');

        ticketList.appendChild(row);
      }

      card.appendChild(ticketList);
    }

    this.detailEl.appendChild(card);
  }
}
