<template>
  <MainLayout>
    <!-- Page header -->
    <div class="d-flex align-center justify-space-between mb-4">
      <h1 class="text-h5 font-weight-bold">Тематические группы</h1>
      <v-btn variant="text" prepend-icon="mdi-arrow-left" @click="router.push('/')">
        Назад
      </v-btn>
    </div>

    <!-- Loading -->
    <div v-if="loading" class="d-flex justify-center py-10">
      <v-progress-circular indeterminate color="primary" size="48" />
    </div>

    <!-- Empty state -->
    <v-card v-else-if="groups.length === 0" variant="flat" class="pa-10 text-center">
      <v-icon size="64" color="grey-lighten-1" class="mb-4">mdi-folder-open-outline</v-icon>
      <div class="text-h6 text-grey mb-2">Нет тематических групп</div>
      <div class="text-body-2 text-grey">Группы создаются автоматически при создании тикетов</div>
    </v-card>

    <!-- Groups grid -->
    <v-row v-else>
      <v-col v-for="group in groups" :key="group.id" cols="12" sm="6" md="4" lg="3">
        <v-card
          variant="outlined"
          class="group-card-hover"
          style="cursor: pointer"
          @click="loadGroupDetail(group.id)"
        >
          <v-card-text class="text-center">
            <v-chip color="info" size="x-small" label class="mb-2">
              {{ group.autoGenerated ? 'Автоматическая' : 'Ручная' }}
            </v-chip>
            <div class="text-h4 font-weight-bold mb-1">{{ group.ticketCount }}</div>
            <div class="text-subtitle-2 font-weight-medium">{{ group.name }}</div>
          </v-card-text>
        </v-card>
      </v-col>
    </v-row>

    <!-- Group detail -->
    <v-card v-if="selectedGroup" class="mt-6" variant="outlined">
      <v-card-title class="d-flex align-center justify-space-between">
        <span class="text-h6">{{ selectedGroup.name }}</span>
        <v-chip color="orange" size="small" label variant="tonal">
          {{ selectedGroup.ticketCount }} тикетов
        </v-chip>
      </v-card-title>

      <v-card-text>
        <p v-if="selectedGroup.description" class="text-body-2 text-grey mb-4">
          {{ selectedGroup.description }}
        </p>

        <v-list v-if="selectedGroup.tickets?.length" density="compact">
          <v-list-item
            v-for="t in selectedGroup.tickets"
            :key="t.id"
            :to="`/tickets/${t.id}`"
            class="rounded"
          >
            <template #default>
              <div class="d-flex align-center justify-space-between w-100">
                <span class="text-body-2">#{{ t.number }} {{ t.title }}</span>
                <v-chip size="x-small" label variant="tonal" :color="statusColorMap[t.status]">
                  {{ t.status }}
                </v-chip>
              </div>
            </template>
          </v-list-item>
        </v-list>
      </v-card-text>
    </v-card>
  </MainLayout>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { useRouter } from 'vue-router';
import { api } from '@/services/api.js';
import { toast } from '@/composables/useToast.js';
import MainLayout from '@/components/layout/MainLayout.vue';

const router = useRouter();

const groups = ref([]);
const loading = ref(false);
const selectedGroup = ref(null);

const statusColorMap = {
  OPEN: 'blue',
  IN_PROGRESS: 'orange',
  WAITING_FOR_USER: 'amber',
  RESOLVED: 'green',
  CLOSED: 'grey'
};

async function loadGroups() {
  loading.value = true;
  try {
    const res = await api.get('/topic-groups');
    groups.value = res.data || [];
  } catch (err) {
    toast.error(err.message);
  }
  loading.value = false;
}

async function loadGroupDetail(groupId) {
  try {
    const res = await api.get(`/topic-groups/${groupId}`);
    selectedGroup.value = res.data;
  } catch (err) {
    toast.error(err.message);
  }
}

onMounted(loadGroups);
</script>

<style scoped>
.group-card-hover:hover {
  border-color: rgb(var(--v-theme-primary));
}
</style>
