import { el, clearEl } from '../../utils/dom.js';
import { AdminLayout } from '../../components/layout/AdminLayout.js';
import { Button } from '../../components/ui/Button.js';
import { Badge } from '../../components/ui/Badge.js';
import { Spinner } from '../../components/ui/Spinner.js';
import { Toast } from '../../components/ui/Toast.js';

export class AdminTopicGroupsPage {
  constructor(router) { this.router = router; this.groups = []; }

  async render(container) {
    clearEl(container);

    const user = window.__auth.getUser();
    const layout = new AdminLayout({ user, router: this.router, auth: window.__auth });
    layout.mount(container);

    this.content = layout.getContent();
    this._renderContent();
    await this._load();
  }

  _renderContent() {
    clearEl(this.content);

    this.content.appendChild(el('div', { class: 'page-header' }, [
      el('h1', {}, 'Тематические группы'),
      new Button({
        text: 'Переклассифицировать всё',
        variant: 'secondary',
        onClick: async () => {
          await window.__api.post('/topic-groups/reclassify');
          Toast.info('Переклассификация запущена. Обновите через минуту.');
        }
      }).el
    ]));

    this.listEl = el('div');
    this.content.appendChild(this.listEl);
  }

  async _load() {
    clearEl(this.listEl);
    new Spinner().mount(this.listEl);

    try {
      const res = await window.__api.get('/topic-groups');
      this.groups = res.data || [];
      this._renderGroups();
    } catch (err) { Toast.error(err.message); }
  }

  _renderGroups() {
    clearEl(this.listEl);

    if (this.groups.length === 0) {
      this.listEl.appendChild(el('div', { class: 'empty-state' }, [
        el('div', { class: 'empty-state__icon' }, '\uD83D\uDCC2'),
        el('div', { class: 'empty-state__title' }, 'Нет групп')
      ]));
      return;
    }

    const grid = el('div', { class: 'flex-col gap-sm' });

    for (const g of this.groups) {
      const card = el('div', { class: 'card flex items-center justify-between gap-md', style: { padding: 'var(--space-md) var(--space-lg)' } });

      const info = el('div', { class: 'flex items-center gap-md', style: { flex: '1' } }, [
        new Badge(String(g.ticketCount), 'in-progress').el,
        el('div', {}, [
          el('div', { style: { fontWeight: 'var(--font-weight-medium)' } }, g.name),
          el('div', { class: 'text-xs text-muted' }, g.autoGenerated ? 'Автоматическая' : 'Ручная')
        ])
      ]);

      const actions = el('div', { class: 'flex gap-xs' });

      new Button({
        text: 'Удалить', variant: 'danger', size: 'sm',
        onClick: async () => {
          if (confirm(`Удалить группу "${g.name}"? Тикеты будут откреплены.`)) {
            await window.__api.delete(`/topic-groups/${g.id}`);
            Toast.success('Группа удалена');
            await this._load();
          }
        }
      }).mount(actions);

      card.appendChild(info);
      card.appendChild(actions);
      grid.appendChild(card);
    }

    this.listEl.appendChild(grid);
  }
}
