<template>
  <AdminLayout>
    <v-container fluid>
      <div class="d-flex align-center justify-space-between mb-6">
        <div class="text-h5 font-weight-bold">Тематические группы</div>
        <v-btn
          color="secondary"
          variant="outlined"
          prepend-icon="mdi-refresh"
          @click="reclassify"
        >
          Переклассифицировать всё
        </v-btn>
      </div>

      <v-row v-if="loading" justify="center" class="my-10">
        <v-progress-circular indeterminate color="primary" size="48" />
      </v-row>

      <template v-else>
        <v-alert v-if="groups.length === 0" type="info" variant="tonal">
          <template #prepend>
            <v-icon icon="mdi-folder-open-outline" />
          </template>
          Нет групп
        </v-alert>

        <div v-else class="d-flex flex-column" style="gap: 8px">
          <v-card v-for="g in groups" :key="g.id" variant="outlined">
            <v-card-text class="d-flex align-center justify-space-between">
              <div class="d-flex align-center" style="gap: 12px; flex: 1">
                <v-chip color="primary" size="small" label>
                  {{ g.ticketCount }}
                </v-chip>
                <div>
                  <div class="font-weight-medium">{{ g.name }}</div>
                  <div class="text-caption text-medium-emphasis">
                    {{ g.autoGenerated ? 'Автоматическая' : 'Ручная' }}
                  </div>
                </div>
              </div>

              <v-btn
                color="error"
                variant="text"
                size="small"
                prepend-icon="mdi-delete-outline"
                @click="deleteGroup(g)"
              >
                Удалить
              </v-btn>
            </v-card-text>
          </v-card>
        </div>
      </template>
    </v-container>
  </AdminLayout>
</template>

<script setup>
import { ref, onMounted } from 'vue';
import { api } from '@/services/api.js';
import { toast } from '@/composables/useToast.js';
import AdminLayout from '@/components/layout/AdminLayout.vue';

const groups = ref([]);
const loading = ref(false);

async function load() {
  loading.value = true;
  try {
    const res = await api.get('/topic-groups');
    groups.value = res.data || [];
  } catch (err) { toast.error(err.message); }
  loading.value = false;
}

async function reclassify() {
  await api.post('/topic-groups/reclassify');
  toast.info('Переклассификация запущена. Обновите через минуту.');
}

async function deleteGroup(g) {
  if (confirm(`Удалить группу "${g.name}"? Тикеты будут откреплены.`)) {
    await api.delete(`/topic-groups/${g.id}`);
    toast.success('Группа удалена');
    await load();
  }
}

onMounted(load);
</script>
